<a href="https://colab.research.google.com/github/Anngel-o/IA-Machine-Learning/blob/main/1_Vectores_Matrices_Arreglos_Operaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Definición y tipos de aprendizaje**

El Machine Learning (ML) es un campo de la inteligencia artificial que se centra en el desarrollo de algoritmos y técnicas que permiten a las computadoras aprender y hacer predicciones o decisiones basadas en datos. En lugar de seguir instrucciones específicas, los sistemas de ML aprenden patrones y regularidades a partir de los datos. Hay tres tipos principales de aprendizaje:

### **Aprendizaje Supervisado:**
El algoritmo aprende de un conjunto de datos etiquetados y hace predicciones basadas en esa experiencia.

### **Aprendizaje No Supervisado:**  
El algoritmo encuentra estructuras ocultas en datos no etiquetados.

### **Aprendizaje por Refuerzo:**
El algoritmo aprende a tomar decisiones mediante la experimentación y la obtención de recompensas.




---



---



---

# **Vectores, matrices, arreglos y operaciones**



Transpuesta, Determinante y Traza

    Transpuesta: La transpuesta de una matriz es una nueva matriz cuyos renglones son las columnas de la matriz original y viceversa.
    Determinante: Es un valor único que puede calcularse a partir de una matriz cuadrada y proporciona información sobre las propiedades de la matriz, como si es invertible.
    Traza: Es la suma de los elementos en la diagonal principal de una matriz cuadrada.

Valores y Vectores Característicos

    Valores Característicos: Son valores que indican cuánto se estira o se encoge un vector en una dirección particular cuando una matriz actúa sobre él.
    Vectores Característicos: Son los vectores que se escalan por la matriz por un valor característico correspondiente.

Producto Punto

El producto punto es una operación algebraica que toma dos secuencias de números (generalmente vectores) y devuelve un solo número, calculado como la suma de los productos de los elementos correspondientes.
Operaciones con Matrices

    Adición y Sustracción: Se realizan elemento a elemento.
    Multiplicación: Puede ser escalar o matriz por matriz. La multiplicación de matrices implica una combinación lineal de filas
    y columnas.
    Inversión: La matriz inversa de una matriz cuadrada 𝐴
        A es la matriz
        𝐴-1es la inversa de la matriz A
        𝐴𝐴-1=𝐼
        𝐼 es la matriz identidad.


In [ ]:
print("Hola mundo")

Hola mundo


**Jose Angel Ortiz Meraz 353195**

#Operaciones Matriciales
*Ejercicio 1: Creación de Vectores*


In [ ]:
import numpy as np

# Creación básica de vectores
vector_lista = [1, 2, 3, 4, 5]
vector_numpy = np.array(vector_lista)
print("Vector numpy:", vector_numpy)
print("Tipo:", type(vector_numpy))

# Acceso y modificación de elementos
vector_numpy[2] = 10
print("Vector modificado:", vector_numpy)

# Operaciones con vectores
vector1 = np.array([1, 2, 3, 4])
vector2 = np.array([5, 6, 7, 8])

# Suma y resta
suma_vectores = vector1 + vector2
resta_vectores = vector1 - vector2
print("Suma:", suma_vectores)
print("Resta:", resta_vectores)

# Producto punto
producto_punto = np.dot(vector1, vector2)
print("Producto punto:", producto_punto)

# Magnitud (norma) de un vector
magnitud_vector1 = np.linalg.norm(vector1)
print("Magnitud de vector1:", magnitud_vector1)


Vector numpy: [1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>
Vector modificado: [ 1  2 10  4  5]
Suma: [ 6  8 10 12]
Resta: [-4 -4 -4 -4]
Producto punto: 70
Magnitud de vector1: 5.477225575051661


*Ejercicio 2 Ejercicio 2: Creación de Matrices*

In [ ]:
import numpy as np

# Creación básica de matrices
matriz_lista = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz_numpy = np.array(matriz_lista)
print("Matriz numpy:\n", matriz_numpy)
print("Forma de la matriz:", matriz_numpy.shape)

# Acceso y modificación de elementos en una matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print("Elemento en posición (2,3):", matriz_4x4[1, 2])
matriz_4x4[3] = [17, 18, 19, 20]
print("Matriz modificada:\n", matriz_4x4)

# Operaciones con matrices
matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Suma, resta, multiplicación Hadamard y producto matricial
suma_matrices = matriz1 + matriz2
resta_matrices = matriz1 - matriz2
hadamard = matriz1 * matriz2
producto_matrices = np.dot(matriz1, matriz2)

print("Suma de matrices:\n", suma_matrices)
print("Resta de matrices:\n", resta_matrices)
print("Multiplicación Hadamard:\n", hadamard)
print("Producto matricial:\n", producto_matrices)

# Transpuesta y determinante
transpuesta_matriz1 = matriz1.T
determinante_matriz1 = np.linalg.det(matriz1)

print("Transpuesta de matriz1:\n", transpuesta_matriz1)
print("Determinante de matriz1:", determinante_matriz1)

Matriz numpy:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Forma de la matriz: (3, 3)
Elemento en posición (2,3): 7
Matriz modificada:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [17 18 19 20]]
Suma de matrices:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Resta de matrices:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Multiplicación Hadamard:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Producto matricial:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpuesta de matriz1:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Determinante de matriz1: 0.0


*Ejercicio 2: Creación de Matrices*

In [ ]:
import numpy as np
from scipy.linalg import lu

# Multiplicación de matrices
matriz_2x3 = np.array([[1, 2, 3], [4, 5, 6]])
matriz_3x2 = np.array([[7, 8], [9, 10], [11, 12]])

multiplicacion = np.dot(matriz_2x3, matriz_3x2)
print("Multiplicación de matrices:\n", multiplicacion)

# Sistema de ecuaciones lineales
A = np.array([[2, 3], [4, 5]])
b = np.array([5, 6])
solucion = np.linalg.solve(A, b)
print("Solución del sistema de ecuaciones:", solucion)

# Descomposición LU y cálculo de inversa
matriz_cuadrada = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

# Descomposición LU
P, L, U = lu(matriz_cuadrada)

print("Matriz P (permute):\n", P)
print("Matriz L (lower triangular):\n", L)
print("Matriz U (upper triangular):\n", U)

# Cálculo de la inversa
inversa_matriz = np.linalg.inv(matriz_cuadrada)
print("Matriz inversa:\n", inversa_matriz)


Multiplicación de matrices:
 [[ 58  64]
 [139 154]]
Solución del sistema de ecuaciones: [-3.5  4. ]
Matriz P (permute):
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Matriz L (lower triangular):
 [[1.  0.  0. ]
 [0.  1.  0. ]
 [0.2 0.8 1. ]]
Matriz U (upper triangular):
 [[ 5.   6.   0. ]
 [ 0.   1.   4. ]
 [ 0.   0.  -0.2]]
Matriz inversa:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
