<a href="https://colab.research.google.com/github/Anngel-o/IA-Machine-Learning/blob/main/1_vectores_matrices_arreglos_operaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Definición y tipos de aprendizaje**

El Machine Learning (ML) es un campo de la inteligencia artificial que se centra en el desarrollo de algoritmos y técnicas que permiten a las computadoras aprender y hacer predicciones o decisiones basadas en datos. En lugar de seguir instrucciones específicas, los sistemas de ML aprenden patrones y regularidades a partir de los datos. Hay tres tipos principales de aprendizaje:

### **Aprendizaje Supervisado:**
El algoritmo aprende de un conjunto de datos etiquetados y hace predicciones basadas en esa experiencia.

### **Aprendizaje No Supervisado:**  
El algoritmo encuentra estructuras ocultas en datos no etiquetados.

### **Aprendizaje por Refuerzo:**
El algoritmo aprende a tomar decisiones mediante la experimentación y la obtención de recompensas.




---



---



---

# **Vectores, matrices, arreglos y operaciones**



##Transpuesta, Determinante y Traza

**Transpuesta:** La transpuesta de una matriz es una nueva matriz cuyos renglones son las columnas de la matriz original y viceversa.

**Determinante:** Es un valor único que puede calcularse a partir de una matriz cuadrada y proporciona información sobre las propiedades de la matriz, como si es invertible.

**Traza:** Es la suma de los elementos en la diagonal principal de una matriz cuadrada.

##Valores y Vectores Característicos

**Valores Característicos:** Son valores que indican cuánto se estira o se encoge un vector en una dirección particular cuando una matriz actúa sobre él.

**Vectores Característicos:** Son los vectores que se escalan por la matriz por un valor característico correspondiente.

##Producto Punto

El producto punto es una operación algebraica que toma dos secuencias de números (generalmente vectores) y devuelve un solo número, calculado como la suma de los productos de los elementos correspondientes.
Operaciones con Matrices

**Adición y Sustracción:** Se realizan elemento a elemento.

**Multiplicación:** Puede ser escalar o matriz por matriz. La multiplicación de matrices implica una combinación lineal de filas y columnas.

**Inversión:** La matriz inversa de una matriz cuadrada 𝐴
        A es la matriz
        𝐴-1es la inversa de la matriz A
        𝐴𝐴-1=𝐼
        𝐼 es la matriz identidad.


In [ ]:
print("Hola mundo")

Hola mundo


**Jose Angel Ortiz Meraz 353195**

#Operaciones Matriciales
*Ejercicio 1: Creación de Vectores*


In [ ]:
# Crea un vector de 5 elementos utilizando una lista en Python.
# Convierte este vector en un array de NumPy.
# Imprime el vector resultante y su tipo.

# Creación básica de vectores
import numpy as np

vector=[1,2,3,4,5]
vector_numpy = np.array(vector)

print("vector en python: ", vector)
print("tipo: ", type(vector))

print("vector con numpy: ", vector_numpy)
print("tipo: ", type(vector_numpy))

# Acceso y modificación de elementos
# Accede al tercer elemento del vector y cámbialo por un nuevo valor.
# Imprime el vector modificado.

vector[2] = 6
print("vector modificado: ", vector)

vector en python:  [1, 2, 3, 4, 5]
tipo:  <class 'list'>
vector con numpy:  [1 2 3 4 5]
tipo:  <class 'numpy.ndarray'>
vector modificado:  [1, 2, 6, 4, 5]


In [ ]:
# Crea dos vectores de 4 elementos.
# Calcula la suma y la resta de los dos vectores.
# Calcula el producto punto (dot product) de los dos vectores.
# Encuentra la magnitud (norma) de uno de los vectores.

# Creación de vectores con Numpy
vector1 = np.array([1,2,3,4])
vector2 = np.array([1,1,1,1])
print("vector con numpy: ", vector1)
print("tipo: ", type(vector1))

# Suma y resta de vectores
suma = vector1 + vector2
resta = vector1 - vector2;
print("suma de vectores: ", suma)
print("resta de vectores: ", resta)

# Producto punto
# En NumPy, la función .dot se utiliza para calcular el producto punto
# (también conocido como producto escalar) entre dos arreglos.
producto_punto = np.dot(vector1, vector2)
print("producto punto de vectores: ", producto_punto)

# Magnitud (norma) de un vector
magnitud_vector1 = np.linalg.norm(vector1)
#linag: linear algebra
print("magnitud del vector 1: ", magnitud_vector1)

vector con numpy:  [1 2 3 4]
tipo:  <class 'numpy.ndarray'>
suma de vectores:  [2 3 4 5]
resta de vectores:  [0 1 2 3]
producto punto de vectores:  10
magnitud del vector 1:  5.477225575051661


*Ejercicio 2: Creación de Matrices*

In [ ]:
# Crea una matriz 3x3 utilizando listas anidadas en Python.
#   Convierte esta matriz en un array de NumPy.
#   Imprime la matriz resultante y su forma (dimensión).

import numpy as np

# Creación básica de matrices
matriz = [[1,2,3], [4,5,6], [7,8,9]]
print("matriz en python: ", matriz)

# Creación de matrices con Numpy
matriz_numpy = np.array(matriz)
print("matriz con numpy: ", matriz)
print("forma de la matriz: ", matriz_numpy.shape)

matriz en python:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz con numpy:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
forma de la matriz:  (3, 3)


In [ ]:
# Acceso y modificación de elementos:
#   Accede al elemento en la posición (2, 3) de una matriz 4x4.
#   Modifica este elemento y cambia la última fila de la matriz por un nuevo vector de 4 elementos.

matriz1 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print("matriz 4x4: \n", matriz1)

vector_nuevo = np.array([17,18,19,20])

matriz1[2][3] = 120
matriz1[3] = vector_nuevo
print("matriz 4x4 modificada: \n", matriz1)


matriz 4x4: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
matriz 4x4 modificada: 
 [[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11 120]
 [ 17  18  19  20]]


In [ ]:
# Operaciones con matrices:

#     Crea dos matrices 3x3 y realiza las siguientes operaciones:
#         Suma de matrices.
#         Resta de matrices.
#         Producto elemento a elemento (multiplicación Hadamard).
#         Multiplicación de matrices (producto matricial).
#     Calcula la transpuesta de una de las matrices.
#     Encuentra el determinante de una matriz 3x3.

matriz1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
matriz2 = np.array([[9,8,7], [6,5,4], [3,2,1]])

# Suma de matrices
matriz_suma = matriz1 + matriz2
print("suma de matrices: \n", matriz_suma)

# Resta de matrices
matriz_resta = matriz1 - matriz2
print("resta de matrices: \n", matriz_resta)

# Producto elemento a elemento (multiplicación Hadamard)
matriz_hadamard = matriz1 * matriz2
print("multiplicación hadamard: \n", matriz_hadamard)

# Multiplicación de matrices (producto matricial)
# En NumPy, la función .dot se utiliza para calcular el producto punto
# (también conocido como producto escalar) entre dos arreglos.
matriz_hadamard = np.dot(matriz1, matriz2)
print("producto matricial: \n", matriz_hadamard)

# Transpuesta de una matriz
matriz_transpuesta = matriz1.T
print("transpuesta de la matriz 1: \n", matriz_transpuesta)

# Determinante de una matriz
determinante_matriz = np.linalg.det(matriz1)
print("determinante de la matriz 1: \n", determinante_matriz)

suma de matrices: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
resta de matrices: 
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
multiplicación hadamard: 
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
producto matricial: 
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
transpuesta de la matriz 1: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
determinante de la matriz 1: 
 0.0


*Ejercicio 3: Aplicación de Operaciones con Matrices*

In [14]:
# Multiplicación de matrices:

#     Crea una matriz 2x3 y otra matriz 3x2. Realiza la multiplicación matricial y muestra el resultado.
#     Verifica si la multiplicación inversa da la matriz identidad.

import numpy as np

matriz1 = np.array([[1,2,3],[4,5,6]])
matriz2 = np.array([[1,2],[4,5], [6,7]])

matriz_multiplicacion = np.dot(matriz1, matriz2)

print("producto matricial: \n", matriz_multiplicacion)

inversa = np.linalg.inv(matriz_multiplicacion)
print("inversa de la matriz resultante: \n", inversa)

identidad = np.dot(matriz_multiplicacion, inversa)
print("matriz de identidad: \n", identidad)

producto matricial: 
 [[27 33]
 [60 75]]
inversa de la matriz resultante: 
 [[ 1.66666667 -0.73333333]
 [-1.33333333  0.6       ]]
matriz de identidad: 
 [[1.00000000e+00 2.10942375e-15]
 [5.55111512e-15 1.00000000e+00]]


In [10]:
# Sistemas de ecuaciones lineales:

#     Utiliza la función np.linalg.solve() para resolver el sistema:

# {2x+3y=5
# {4x+5y=6
from scipy.linalg import lu

# A⋅x=b

# Donde:

#     A es la matriz de coeficientes,

#     x es el vector de incógnitas (x e y),

#     b es el vector de términos independientes.

A = np.array([[2,3],[4, 5]])
b = np.array([5, 6])
x = np.linalg.solve(A, b)

print("solución del sistema de ecuaciones: ", x)

solución del sistema de ecuaciones:  [-3.5  4. ]


In [29]:
# Descomposición de matrices:

#     Realiza la descomposición de una matriz cuadrada en una matriz triangular superior e inferior (LU descomposición).
#     Utiliza la función np.linalg.inv() para encontrar la inversa de una matriz 3x3.
import numpy as np
from scipy.linalg import lu

matriz_cuadrada = np.array([[6,2,3],[4,5,6],[7,8,9]])
# La descomposición LU descompone una matriz A en el producto de una matriz triangular inferior L
#y una matriz triangular superior U, es decir:

# A=L⋅U

# En Python, podemos usar la función scipy.linalg.lu para realizar esta descomposición.

P, L, U = lu(matriz_cuadrada)

print("Matriz P (permute):\n", P)
print("Matriz L (lower triangular):\n", L)
print("Matriz U (upper triangular):\n", U)

try:
  inversa_matriz = np.linalg.inv(matriz_cuadrada)
  print("inversa de la matriz: \n", inversa_matriz)
except np.linalg.LinAlgError:
  print("la matriz no es invertible (su determinante es cero).")


Matriz P (permute):
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Matriz L (lower triangular):
 [[ 1.          0.          0.        ]
 [ 0.85714286  1.          0.        ]
 [ 0.57142857 -0.08823529  1.        ]]
Matriz U (upper triangular):
 [[ 7.          8.          9.        ]
 [ 0.         -4.85714286 -4.71428571]
 [ 0.          0.          0.44117647]]
inversa de la matriz: 
 [[ 0.2        -0.4         0.2       ]
 [-0.4        -2.2         1.6       ]
 [ 0.2         2.26666667 -1.46666667]]


In [40]:
# Autovalores y autovectores:

#     Calcula los autovalores y autovectores de una matriz 3x3.
#     Verifica que A × v = λ × v, donde A es la matriz, v es el autovector y λ es el autovalor correspondiente.

matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])

autovalores, autovectores = np.linalg.eig(matriz)
print("autovalores de la matriz: \n", autovalores)
print("autovectores de la matriz: \n", autovectores)

for i in range(len(autovalores)):
  lambda_i = autovalores[i]
  v_i = autovectores[:, i] #tomar la columna i como autovector

  #calcular A × v = λ × v
  Av = np.dot(matriz, v_i)
  lambda_v = lambda_i * v_i

  print("A * v = ", Av)
  print("λ * v = ", lambda_v)
  print(f"verificación para autovalor {i+1}: ")
  print("A · v:", Av)
  print("λ · v:", lambda_v)
  print("¿Son iguales?", np.allclose(Av, lambda_v))
  # La función np.allclose(Av, lambda_v) se usa para verificar
  # si los dos arreglos son aproximadamente iguales dentro de un margen de tolerancia.


autovalores de la matriz: 
 [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
autovectores de la matriz: 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
A * v =  [ -3.73863537  -8.46653421 -13.19443305]
λ * v =  [ -3.73863537  -8.46653421 -13.19443305]
verificación para autovalor 1: 
A · v: [ -3.73863537  -8.46653421 -13.19443305]
λ · v: [ -3.73863537  -8.46653421 -13.19443305]
¿Son iguales? True
A * v =  [ 0.87764976  0.09688771 -0.68387434]
λ * v =  [ 0.87764976  0.09688771 -0.68387434]
verificación para autovalor 2: 
A · v: [ 0.87764976  0.09688771 -0.68387434]
λ · v: [ 0.87764976  0.09688771 -0.68387434]
¿Son iguales? True
A * v =  [-9.43689571e-16 -9.99200722e-16 -1.66533454e-16]
λ * v =  [-5.32224203e-16  1.06444841e-15 -5.32224203e-16]
verificación para autovalor 3: 
A · v: [-9.43689571e-16 -9.99200722e-16 -1.66533454e-16]
λ · v: [-5.32224203e-16  1.06444841e-15 -5.32224203e-16]
¿Son iguales? True
